### PR TITLE
Properly set pipeline exit option when validating job status

### LINKED ISSUE #1428: Travis build is green but the tests are actually failing
For example, see #1427.

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes #1428. 

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

### CODE REVIEW

File: scripts/validate_job_status.sh [hunk 1]
```diff
@@ -21,6 +27,7 @@ for i in {1..200}; do
      [[ "$WORKER_1_POD_STATUS" == "Succeeded" ]]; then
       echo "ElasticDL job succeeded."
       kubectl delete pod ${MASTER_POD_NAME}
+      set -e
```
Comment (chunyang-wen) [inline scripts/validate_job_status.sh]: useless?

Comment (terrytangyuan) [reply scripts/validate_job_status.sh]: Fixed.

**Review by chunyang-wen — APPROVED** [review]

**Comment by terrytangyuan** [comment]
Merging this as the Travis failure is expected. See #1427.
